// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvjmwyhxdcburhaaswgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2am13eWh4ZGNidXJoYWFzd2dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNzI5NTgsImV4cCI6MjA1ODY0ODk1OH0.dHe5B7UYkIuSkps_bWbQhDn_3-WGOjnsbeeIYPclU0c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);